name: $(Build.SourceBranchName).customerdev-api.$(Rev:r)
resources:
- repo: self
  fetchDepth: 1
pool:
  vmImage: ubuntu-latest
trigger:
- dev
- staging
- master
variables:
  BuildConfiguration: 'Release'
  DockerImageName: 'vs-dev-asg/ar/$(Build.SourceBranchName)/customerdev-api'
steps:
  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"
    inputs:
      PathtoPublish: "$(build.artifactstagingdirectory)"
  - task: Docker@2
    displayName: "Login to Artifact Registry"
    inputs:
      command: login
      containerRegistry: "gar-vs-dev"
  - task: Docker@2
    displayName: "Build and push image"
    inputs:
      Dockerfile: "Dockerfile"
      command: buildAndPush
      repository: "$(DockerImageName)"
