"""14032025 lenght cust first last name

Revision ID: 1c79caee0c01
Revises: 65dad1d645f3
Create Date: 2025-03-14 10:44:23.377983

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1c79caee0c01'
down_revision = '65dad1d645f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_dev', 'first_name',
               existing_type=sa.VARCHAR(length=40),
               type_=sqlmodel.sql.sqltypes.AutoString(length=80),
               existing_nullable=True)
    op.alter_column('customer_dev', 'last_name',
               existing_type=sa.VARCHAR(length=40),
               type_=sqlmodel.sql.sqltypes.AutoString(length=80),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_dev', 'last_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=80),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('customer_dev', 'first_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=80),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    # ### end Alembic commands ###
