"""5 February 2025 17:13 fixing nullable

Revision ID: 2795625743e7
Revises: b96cf011a128
Create Date: 2025-02-05 17:30:38.155352

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2795625743e7'
down_revision = 'b96cf011a128'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_dev', 'first_name',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('customer_dev', 'postal_code',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('customer_dev', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('customer_dev', 'religion',
               existing_type=postgresql.ENUM('ISLAM', 'KRISTEN', 'KATOLIK', 'HINDU', 'BUDDHA', 'KHONGHUCU', name='religiontypeenum'),
               nullable=True)
    op.alter_column('customer_dev', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', name='gendertypeenum'),
               nullable=True)
    op.alter_column('customer_dev', 'marital_status',
               existing_type=postgresql.ENUM('MARRIED', 'SINGLE', 'DIVORCED', name='maritalstatusenum'),
               nullable=True)
    op.alter_column('customer_dev', 'handphone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_dev', 'handphone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('customer_dev', 'marital_status',
               existing_type=postgresql.ENUM('MARRIED', 'SINGLE', 'DIVORCED', name='maritalstatusenum'),
               nullable=False)
    op.alter_column('customer_dev', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', name='gendertypeenum'),
               nullable=False)
    op.alter_column('customer_dev', 'religion',
               existing_type=postgresql.ENUM('ISLAM', 'KRISTEN', 'KATOLIK', 'HINDU', 'BUDDHA', 'KHONGHUCU', name='religiontypeenum'),
               nullable=False)
    op.alter_column('customer_dev', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('customer_dev', 'postal_code',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('customer_dev', 'first_name',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###
