"""030325 - change customer dev group

Revision ID: 65dad1d645f3
Revises: 6f132ca10965
Create Date: 2025-03-03 18:50:02.497611

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65dad1d645f3'
down_revision = '6f132ca10965'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_dev_group', 'customer_parent_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customer_dev_group', 'customer_reference_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_customer_dev_group_id', table_name='customer_dev_group')
    op.drop_column('customer_dev_group', 'id')
    op.drop_column('customer_dev_group', 'created_at')
    op.drop_column('customer_dev_group', 'created_by')
    op.drop_column('customer_dev_group', 'updated_by')
    op.drop_column('customer_dev_group', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_dev_group', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('customer_dev_group', sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('customer_dev_group', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('customer_dev_group', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('customer_dev_group', sa.Column('id', sa.VARCHAR(length=26), autoincrement=False, nullable=False))
    op.create_index('ix_customer_dev_group_id', 'customer_dev_group', ['id'], unique=False)
    op.alter_column('customer_dev_group', 'customer_reference_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customer_dev_group', 'customer_parent_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
