"""12 February 2025 16:05 fixing field

Revision ID: 6f132ca10965
Revises: 807f874eb695
Create Date: 2025-02-12 16:07:37.588575

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f132ca10965'
down_revision = '807f874eb695'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_dev', 'nationality',
               existing_type=postgresql.ENUM('WNI', 'WNA', 'UNKNOWN', name='nationalityenum'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_dev', 'nationality',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('WNI', 'WNA', 'UNKNOWN', name='nationalityenum'),
               existing_nullable=True)
    # ### end Alembic commands ###
